### ISSUE TITLE
"alias" option no longer works

### ISSUE THREAD

**Issue by WillsonHaw** [vadimdemedes/minimist-options#1]
After upgrading to 2.0, "alias" no longer works. If I rename "alias" to "aliases" it works again. Either the docs should be updated to say "aliases" or "alias" was broken in the update to 2.0

**Comment by vadimdemedes** [comment]
Yes, this was intentional, there's only `aliases` property now. Docs need to be updated.

**Comment by justinanastos** [comment]
I believe this can be closed with the merge of #2
