### ISSUE TITLE
Support `number` type

### ISSUE THREAD

**Issue by sindresorhus** [vadimdemedes/minimist-options#10]
We use this module in `meow`, but we switched to `yargs-parser`, which also supports a `number` type. Not sure what makes the most sense here. I would personally rename this module to `yargs-parser-options` and target `yargs-parser` instead, since `minimist` has not been maintained for years.

**Comment by vadimdemedes** [comment]
It seems to me that a lot of args parsers want to be compatible with `minimist` anyway, do you think it's worth renaming it?

**Comment by sindresorhus** [comment]
I would rename, but doesn't matter much. All I need is support for `number` type.

**Comment by vadimdemedes** [comment]
Fixed via https://github.com/vadimdemedes/minimist-options/pull/8.
