### ISSUE TITLE
Disable type validation (or always allow undefined values)

### ISSUE THREAD

**Issue by pimlie** [vadimdemedes/minimist-options#12]
Unfortunately the type validation introduced in v4 is breaking my setup. To support both cli as programmatic use I set the default values for my flags to `undefined` and then in my library code I only set the default value when the flag is undefined. This way I dont have to repeat my default values both for the flags as in my code where I set the option from programmatic use.

Could we add an option to only check the type of the value when the flag really has a value defined? Maybe through an additional setting?

**Comment by vadimdemedes** [comment]
I think the whole validation of default values should be skipped, unless you set a `default` key:

https://github.com/vadimdemedes/minimist-options/blob/ef0835f648d3c43f981f93be28b85180c1c57d73/index.js#L68

Could you share a bit of code that triggers errors or unexpected behavior?

**Comment by pimlie** [comment]
Sure, check [here](https://github.com/pimlie/eslint-multiplexer/blob/master/bin/eslint-multiplexer) for my option definition and [here](https://github.com/pimlie/eslint-multiplexer/blob/master/lib/index.js#L60) for my internal setOptions method

**Comment by vadimdemedes** [comment]
Why do you need to set `default: undefined`, since it's the default value when trying to access a missing object key anyway?

```js
const obj = {}
obj.default === undefined //=> true
```

**Comment by pimlie** [comment]
Thats probably a code style thing. Imo code that explicitly sets the behaviour it expects is better readable/understandable in the long run.

**Comment by vadimdemedes** [comment]
I agree about explicit code, but I don't think it applies to `undefined` values, it's a pretty uncommon thing to see them being set instead of just skipping the property.

**Comment by pimlie** [comment]
Although I understand your reasoning I still think its not correct to just use hasOwnProperty without checking its value. Anyway, agree to disagree I guess so will close this :)

**Comment by stephenmathieson** [comment]
I'm building a CLI which accepts flags and/or environment variables on _required_ fields. This looks something like:

```js
meow('...', {
  flags: {
    foo: {
      isRequired: true,
      type: 'string',
      default: process.env.FOO
    }
  }
})
```

As `process.env.FOO` is either a string or undefined, I get an error here. I can do:

```
{
  default: process.env.FOO || ''
}
```

However, this prevents the built-in required-ness logic from working.

How are other folks handling this?

**Comment by stephenmathieson** [comment]
Ended up doing something like this:

```ts
function defaulter(name, fallback) {
  const value = process.env[name] || fallback;
  if (value !== undefined) {
    return { default: value };
  }
  return {};
}

meow('...', {
  flags: {
    foo: {
      isRequired: true,
      type: 'string',
      ...defaulter('FOO')
    },
    bar: {
      type: 'string',
      ...defaulter('BAR', 'some value')
    }
  }
})
```

It's not pretty/ideal, however it enables me to do what I need 🤷
