### ISSUE TITLE
Prevent user mistakes

### ISSUE THREAD

**Issue by sindresorhus** [vadimdemedes/minimist-options#4]
This module should throw a user-friendly error if I do dumb stuff. Like for example using an invalid value in `type`, like `type: 'bool'`, or define a boolean type and then use a string in the `default` option.

**Comment by vadimdemedes** [comment]
Agree!

**Comment by vadimdemedes** [comment]
Fixed via https://github.com/vadimdemedes/minimist-options/pull/8.
